name: jawi_converter
description: A Dart package to convert Bahasa Melayu (Rumi) into Jawi
version: 1.0.0
repository: https://github.com/hazmi-badrunsham/jawi_converter

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
